app/home/__init__.py
from controllers import Home

app/home/controllers.py
from flask import Blueprint, Response , request, render_template, \
                flash, g, session, redirect, url_for, \
				jsonify, json, abort, make_response

from flask.ext.login import login_user , logout_user , current_user , login_required
from app.users.forms import UploadProfilePictureForm
from app.users.controllers import getProfilePicture, getUtilization

# @define - blueprint for home
Home = Blueprint('Home', __name__,)


# @function - Renders the home page
@Home.route('/')
@Home.route('/home')
@login_required
def show_home():
	print "Home"
	upload_picture_form = UploadProfilePictureForm(request.form)
	url_for_profile_picture = getProfilePicture()
	utilizationProject = getUtilization(current_user)
	print url_for_profile_picture
	return render_template('home/home.html',user=current_user,upload_picture_form=upload_picture_form, \
		 profile_picture=url_for_profile_picture, utilizationProject=utilizationProject)


# @function - appends feedbacks to text file [this should be saved on a more organized storage]
@Home.route('/feedback',methods=['GET','POST'])
@login_required
def saveFeedback():
	if request.method == 'POST':
		print request.form['feedback']
		with open("feedback.txt", "a") as feedbackFile:
			feedbackFile.write(request.form['feedback']+"\n\n")
		return redirect(url_for('Home.show_home'))

#@Home.route('/sync')
@login_required
def sync_data(user):
	url='http://www.seerlabs.com:5556/api/getProject'
	payload = {'email': 'claudine.bael@seer-technologies.com'}
	response = requests.post(url, data=payload)
	responseJson = response.json()
	print(responseJson['projects'][0])

	#http://www.seerlabs.com:5556/api/getUtilization
	#http://www.seerlabs.com:5556/api/postNewsfeed
	#http://www.seerlabs.com:5556/api/getNewsfeed
	#http://www.seerlabs.com:5556/api/getProject

app/users/controllers.py
import os.path
import random
import requests
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for
from flask.ext.login import login_user , logout_user , current_user , login_required
from werkzeug import check_password_hash, generate_password_hash
from sqlalchemy.exc import DatabaseError, IntegrityError
from sqlalchemy.sql import exists
from sqlalchemy import or_
from flask.ext.uploads import UploadSet, IMAGES, configure_uploads

from app.database import db_session, Base,init_db
from app.users.forms import LoginForm, ChangePasswordForm
from app.users.models import User, ProfileImage
from app.projects.models import Project
from app import login_manager, oid, imageUploadSet

# @define - blueprint for users
Users = Blueprint('Users', __name__,)

# @function - Used to add an object to a database [Could be move to another class to make this more reusable by other objects]
def add_to_db(object):
    try:
        db_session.add(object)
        db_session.flush()
        return True
    except sqlalchemy.exc.IntegrityError as err:
        print "IntegrityError"
        return False


# @functions - User authentication methods
# @function - Assigns current user to g
@Users.before_request
def before_request():
    g.user = current_user   #current user from flask.ext.login

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

@Users.route('/login/', methods=['GET', 'POST'])
@oid.loginhandler
def login():
    if g.user is not None and g.user.is_authenticated():
        return redirect(url_for('Home.show_home'))

    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        print user.username
        if user and check_password_hash(user.password, form.password.data):
            user.authenticated = True;
            login_user(user);
            return redirect(url_for('Home.show_home'))
        flash('Wrong username or password', 'error-message')
    return render_template("users/login.html", form=form)

@Users.route('/change_password/',methods=['GET','POST'])
@login_required
def change_password():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        user = g.user
        print user.username
        if user and check_password_hash(user.password, form.old_password.data):
            if(form.new_password.data == form.confirm_password.data):
                #flash('Password changed ');
                user.password = generate_password_hash(form.new_password.data)
                #if(db_session.commit()):
                flash("Password changed",'error')
                    #return redirect(url_for('Home.show_home'))
                #else:
                    #flash("Password NOT changed",'error')
            else:
                flash("Passwords do not match",'error')
        else:   
            flash('Wrong password', 'error')
    return render_template("users/change_password.html", form=form)

@Users.route('/logout')
def logout():
    user = g.user
    user.authenticated = False
    logout_user()
    print 'logout success'
    return redirect(url_for('Users.login'))

# @function - Uploads a profile picture and updates the user data
@Users.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST' and 'image' in request.files:
        name = str(g.user.id) + "_" + str(ProfileImage.query.filter_by(user_id=g.user.id).count()) + os.path.splitext(request.files['image'].filename)[1].lower()
        print name
        previous_image = ProfileImage.query.filter_by(is_active=1).filter_by(user_id=g.user.id).first()
        try:
            filename = imageUploadSet.save(request.files['image'],name=name)
            image = ProfileImage(user_id=g.user.id,is_active=1,image=filename)
            #image.store()
            if previous_image is not None:
                previous_image.is_active = 0
            #DONT FORGET TO UPDATE is_active
            if(add_to_db(image)):
                current_user.images.append(image);
                db_session.commit()
                flash("Photo saved.")
                print image.id
                print imageUploadSet.url(image.image)
        except:
            print "upload not allowed"
    return redirect(url_for('Home.show_home')+"#uploadComplete")

# @function - Returns the current profile picture of the logged in user
def getProfilePicture():
    #g.user = current_user
    #image = ProfileImage.query.filter_by(is_active=1).filter_by(user_id=g.user.id).first()
    image  = current_user.images.filter_by(is_active=1).first()
    if image is not None:
        print imageUploadSet.url(image.image)
        return imageUploadSet.url(image.image)
    else:
        random_img =  random.randint(1,15)
        url = url_for('static', filename='assets/images/default_profile_image/') + str(random_img) +".jpg"
        return url



# @functions - Basecamp integration methods
@login_required
def syncProjects(username):
    url='http://www.seerlabs.com:5556/api/getProject'
    user = User.query.filter_by(username=username).first()
    payload = {'email': user.email}
    response = requests.post(url, data=payload)
    responseJson = response.json()
    print(responseJson['projects'])

    for projectName in responseJson['projects']:
        print projectName
        (ret, ), = db_session.query(exists().where(Project.project_name==projectName))
        if(ret):
             project = Project.query.filter_by(project_name=projectName).first()
             user.projects.append(project)
             print "Existing"
        else:
            project = Project(projectName)
            if(add_to_db(project)):
                user.projects.append(project)
                db_session.commit()
                print "Project added"
            
def getUtilization(user):
    url='http://www.seerlabs.com:5556/api/getUtilization'
    #user = User.query.filter_by(username=user.username).first() #username is unique
    payload = {'email': user.email}
    response = requests.post(url, data=payload)
    responseJson = response.json()
    return responseJson['projects']

    #http://www.seerlabs.com:5556/api/getUtilization
    #http://www.seerlabs.com:5556/api/postNewsfeed
    #http://www.seerlabs.com:5556/api/getNewsfeed
    #http://www.seerlabs.com:5556/api/getProject

#pragma mark -Test block to install database and add a default user
def add_user(c):
    """try:"""
    db_session.add(c)
    db_session.flush()
    return True
    """except sqlalchemy.exc.IntegrityError as err:
        # @todo: handle as appropriate: return existing instance [session.query(Coupon).filter(Coupon.value==c.value).one()] or re-raise
        #logger.error("Tried to add a duplicate entry for the Coupon value [%s]. Aborting", c.value)
        print "Tried to add a duplicate entry for the Coupon value [%s]. Aborting", c.name
        return False"""
""""
init_db();
u = User('Te','re','suh', 'test@seer-technologies.com', "seer", generate_password_hash("seertech"), )
if(add_user(u)):
    db_session.commit()
else:
    print "aww"
print u.id"""

app/templates/home/home.html
{% from "macros.html" import render_field %}
{% extends "layout.html" %}
{% block body %}

	{% include 'home/navigation.html' %}
	<div class="mainContainer">
		
		{% include 'home/upload_picture_modal.html' %}
		{% include 'home/left_sidebar.html' %}

		<div class="mainContent">
			<div class="upperContent">
				<div id="detailsBox">
					<div class="nickname">
						{{user.first_name + " " + user.last_name}}
						<select>
							<option>@WFH</option>
							<option>@Ecotower</option>
							<option>@Meeting</option>
						</select>
					</div>
					<div id="statBox">
						<table>
							{% for project in utilizationProject %}
								<tr>
									<td>
										<span class="projectUtilizationLabel" style="font-size:10px;">{{project.name}}</span>
									</td>
									<td>
										<div class="projectUtilizationBar" style="width:{{project.percent}}%;">{{ project.percent}}%</div>
									</td>
								</tr>
							{% endfor %}
						</table>
					</div>
				</div>
				<!--div id="appointBox">
					<ul id="appointList">
						<li>Sep 27</li>
						<li>Oct 15</li>
					</ul>
				</div-->
			</div>
			<div class="newsContainer">
				<h4 style="margin-left:0; font-weight:normal;">Headlines and Announcements:</h4>
				<div class="feed">
					<div class="headBar"><a href="#">Game Time</a> by HR </div>
					<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ultricies lectus, et venenatis justo.</div>
					<div></div>
				</div>

				<div class="feed">
					<div class="headBar"><a href="#">ISO: Audit Log</a> by Chris Brock </div>
					<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ultricies lectus, et venenatis justo. Sed scelerisque, lectus sit amet imperdiet egestas, libero quam efficitur felis, vel faucibus eros ante in mauris. </div>
				</div>
				
			</div>
		</div>
		{%include 'home/right_sidebar.html' %}
	</div>

{% endblock %}

app/templates/home/left_sidebar.html
<div class="leftCol">
	<div class="profilePictureContainer">
		<a class="profilePicThumb" href="#" rel="theater" id="u_jsonp_3_9">
			<img class="profilePic" alt="Profile picture" src="{{profile_picture}}">
		</a>
		<div class= "editProfilePicture" data-toggle="modal" data-target="#uploadProfilePicture">
			<!--a href="#"-->
			<img src="{{url_for('static', filename='assets/images/edit.png') }}"/>
			<span>Update</span>
		</div>
	</div>
	{% include 'home/projects_nav.html' %}
</div>

app/templates/home/navigation.html
<!--div class="navigation">
	<div class="menuBar">
		<ul class="nav">
			<li><a href="#">Home</a></li>
			<li><a href="#">Project</a></li>
			<li><a href="#">Caps</a></li>
			<li><a href="#">Logs</a></li>
			<li><a href="#">Feedback</a></li>
			<li style="float:right;"><a href="{{ url_for('Users.logout') }}">Logout <i>{{user.username}}</i> from Iris</a></li>
		</ul>
	</div>
</div-->
<nav class="navbar navbar-custom">
  <div class="container-fluid">
    <!--div class="navbar-header">
      <a class="navbar-brand" href="#">Iris</a>
    </div-->
    <div>
      	<ul class="nav navbar-nav">
	        <!--li class="active"><a href="#">Home</a></li-->
	        <li><a href="{{url_for('Home.show_home')}}">Home</a></li>
			<li><a href="#">Project</a></li>
			<li><a href="#">Caps</a></li>
			<li><a href="#">Logs</a></li>
			<!--li><a href="#">Feedback</a></li-->
			<!--li style="float:right;"><a href="{{ url_for('Users.logout') }}">Logout <i>{{user.username}}</i> from Iris</a></li-->
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
	          <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{user.username}}
	          <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="{{ url_for('Users.logout') }}">Logout</a></li>
	            <li data-toggle="modal" data-target="#changePassword"><a>Change password</a></li>
	          </ul>
	        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/home/projects_nav.html
<div class="projectsContainer">
	<ul id="projectNav">
		{% for project in utilizationProject %}
		    <li>
		    	<div class="projectItem">
		    		<a href="#">{{project.name}}</a>
					<!--a><h4>Project Manager</h4></a-->
					<div>
						<!--a class="conn" href="#">N connections
						<span class="rate">{{project.percent}}</span>
						</a-->
					</div>
		    	</div>
		    </li>
		{% endfor %}
	</ul>
</div>

app/templates/home/right_sidebar.html
<div class="rightCol">
	<!--div id="capContainer">
		<ul>
			<li><div class="capBox">Prof</div></li>
			<li><div class="capBox">Student</div></li>
			<li><div class="capBox">Collector</div></li>
			<li><div class="capBox">Tutor</div></li>
		</ul>
	</div-->
	
	<div id="chatBox">
		<form action="{{url_for('Home.saveFeedback')}}" method="post">
			<div class="form-group">
		        <label for="InputMessage">Feedback</label>
		        <div class="input-group">
		            <textarea name="feedback" id="InputMessage" class="form-control" rows="8" cols="60" style="resize:none" placeholder="Say something about Iris..." required></textarea>
		            <!--span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span-->
		        </div>
		        <input type="submit" class="btn btn-default navbar-btn" value="Send" style="float:right">
	    	</div>
		</form>
	</div>
</div>

app/templates/home/upload_picture_modal.html
{% from "macros.html" import render_field %}
<div class="modal fade" id="uploadProfilePicture" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal">
        			<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        		</button>
          		<h4 class="modal-title" id="myModalLabel">Upload profile picture</h4>
	      	</div>
	      	<div class="modal-body">
	      		<form role="form" action="{{url_for('Users.upload')}}" method="post" enctype="multipart/form-data">
				 	{{ render_field(upload_picture_form.image, placeholder="Image", autofocus="", accept="image/*") }}
			        <div class="modal-footer">
				        <!--button type="button" class="btn btn-default" data-dismiss="modal">Close</button-->
				        <button type="submit" class="btn btn-primary">Upload</button>
				    </div>
		    	</form>
	      </div>
    	</div>
  	</div>
</div>

<div class="modal fade" id="uploadComplete" tabindex="-1" role="dialog" aria-labelledby="MyModalTitle" aria-hidden="true">
	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal">
        			<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        		</button>
          		<h4 class="modal-title" id="myModalLabel">Modal title</h4>
	      	</div>
	      	<div class="modal-body">
	      		Ayan, okay na
		    	<div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Yey</button>
			    </div>
	      </div>  
    	</div>
  	</div>
</div>