app/users/models.py
# Import the database object (db) from the main application module
from sqlalchemy import Table, Column, ForeignKey, Integer, Float, String, Boolean, DateTime, Text
from sqlalchemy.exc import DatabaseError, IntegrityError
from sqlalchemy.orm import relationship, backref
from app.database import Base
from app.projects.models import Project

# @definition - Creates a table for the pivot table for users-projects relationship
user_projects = Table('user_projects',Base.metadata,
    Column('id',Integer,primary_key=True,autoincrement=True),
    Column('user_id', Integer, ForeignKey('users.id')),
    Column('project_id', Integer, ForeignKey(Project.id))
)

class User(Base):

    __tablename__ = 'users'
    id = Column(Integer, primary_key=True,autoincrement=True)
    first_name = Column(String(50), unique=True)
    middle_name = Column(String(50), unique=True)
    last_name = Column(String(50), unique=True)
    email = Column(String(255), nullable=False, unique=True)
    username = Column(String(50), nullable=False, unique=True)
    password = Column(String(255), nullable=False, default='')
    

    #One-to-many
    images = relationship('ProfileImage', backref='users',lazy='dynamic')
    #comments = relationship('Comment', backref='users',lazy='dynamic')
    logs = relationship('Log',backref='users',lazy='dynamic')

    #Many-to-many
    projects = relationship('Project', secondary=user_projects, backref=backref('users', lazy='dynamic'))
    

    def __init__(self, fname=None,mname=None,lname=None, email=None, username=None, password=None):
        self.first_name = fname
        self.middle_name = mname
        self.last_name = lname
        self.email = email
        self.username = username
        self.password = password

    def is_authenticated(self):
        return True
 
    def is_active(self):
        return True
 
    def is_anonymous(self):
        return False
 
    def get_id(self):
        return unicode(self.id)

    def __repr__(self):
        return '<User %r>' % (self.name)

class Log(Base):
    __tablename__ = 'logs'
    id = Column(Integer, primary_key=True,autoincrement=True)
    user_id = Column(Integer, ForeignKey('users.id'))
    date = Column(DateTime)
    description = Column(Text)
    hours = Column(Float, nullable=False, unique=True)

    def __init__(self, user_id=None,date=None,description=None, hours=None):
        self.user_id = user_id
        self.date = date
        self.description = description
        self.hours = hours

    # Return object data in easily serializeable format
    @property
    def serialize(self):
        return {
            'id'                : self.id,
            'user_id'           : self.user_id,
            'date'              : self.date,
            'description'       : self.description,
            'hours'             : self.hours
        }
    
class ProfileImage(Base):
    __tablename__ = 'profileImages'
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey('users.id'))
    is_active = Column(Integer)
    image = Column(String(200))

    def __init__(self, user_id=None,is_active=None,image=None):
        self.user_id = user_id
        self.is_active = is_active
        self.image = image

    # Return object data in easily serializeable format
    @property
    def serialize(self):
        return {
            'id'                : self.id,
            'user_id'           : self.user_id,
            'is_active'         : self.is_active,
            'image'             : self.image
        }

app/users/forms.py
# Import Form and RecaptchaField (optional)
from flask.ext.wtf import Form # , RecaptchaField

from wtforms import TextField, PasswordField, FileField

# Import Form validators
from wtforms.validators import Required, Email, EqualTo


# Define the login form (WTForms)
class LoginForm(Form):
    username    = TextField('Username')
    password 	= PasswordField('Password',)

class ChangePasswordForm(Form):
	old_password = PasswordField('Old password')
	new_password = PasswordField('New password')
	confirm_password = PasswordField('Confirm password')

class UploadProfilePictureForm(Form):
	image = FileField('Image')

app/users/__init__.py
from controllers import Users

app/users/controllers.py
import os.path
import random
import requests
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for
from flask.ext.login import login_user , logout_user , current_user , login_required
from werkzeug import check_password_hash, generate_password_hash
from sqlalchemy.exc import DatabaseError, IntegrityError
from sqlalchemy.sql import exists
from sqlalchemy import or_
from flask.ext.uploads import UploadSet, IMAGES, configure_uploads

from app.database import db_session, Base,init_db
from app.users.forms import LoginForm, ChangePasswordForm
from app.users.models import User, ProfileImage
from app.projects.models import Project
from app import login_manager, oid, imageUploadSet

# @define - blueprint for users
Users = Blueprint('Users', __name__,)

# @function - Used to add an object to a database [Could be move to another class to make this more reusable by other objects]
def add_to_db(object):
    try:
        db_session.add(object)
        db_session.flush()
        return True
    except sqlalchemy.exc.IntegrityError as err:
        print "IntegrityError"
        return False


# @functions - User authentication methods
# @function - Assigns current user to g
@Users.before_request
def before_request():
    g.user = current_user   #current user from flask.ext.login

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

@Users.route('/login/', methods=['GET', 'POST'])
@oid.loginhandler
def login():
    if g.user is not None and g.user.is_authenticated():
        return redirect(url_for('Home.show_home'))

    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        print user.username
        if user and check_password_hash(user.password, form.password.data):
            user.authenticated = True;
            login_user(user);
            return redirect(url_for('Home.show_home'))
        flash('Wrong username or password', 'error-message')
    return render_template("users/login.html", form=form)

@Users.route('/change_password/',methods=['GET','POST'])
@login_required
def change_password():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        user = g.user
        print user.username
        if user and check_password_hash(user.password, form.old_password.data):
            if(form.new_password.data == form.confirm_password.data):
                #flash('Password changed ');
                user.password = generate_password_hash(form.new_password.data)
                #if(db_session.commit()):
                flash("Password changed",'error')
                    #return redirect(url_for('Home.show_home'))
                #else:
                    #flash("Password NOT changed",'error')
            else:
                flash("Passwords do not match",'error')
        else:   
            flash('Wrong password', 'error')
    return render_template("users/change_password.html", form=form)

@Users.route('/logout')
def logout():
    user = g.user
    user.authenticated = False
    logout_user()
    print 'logout success'
    return redirect(url_for('Users.login'))

# @function - Uploads a profile picture and updates the user data
@Users.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST' and 'image' in request.files:
        name = str(g.user.id) + "_" + str(ProfileImage.query.filter_by(user_id=g.user.id).count()) + os.path.splitext(request.files['image'].filename)[1].lower()
        print name
        previous_image = ProfileImage.query.filter_by(is_active=1).filter_by(user_id=g.user.id).first()
        try:
            filename = imageUploadSet.save(request.files['image'],name=name)
            image = ProfileImage(user_id=g.user.id,is_active=1,image=filename)
            #image.store()
            if previous_image is not None:
                previous_image.is_active = 0
            #DONT FORGET TO UPDATE is_active
            if(add_to_db(image)):
                current_user.images.append(image);
                db_session.commit()
                flash("Photo saved.")
                print image.id
                print imageUploadSet.url(image.image)
        except:
            print "upload not allowed"
    return redirect(url_for('Home.show_home')+"#uploadComplete")

# @function - Returns the current profile picture of the logged in user
def getProfilePicture():
    #g.user = current_user
    #image = ProfileImage.query.filter_by(is_active=1).filter_by(user_id=g.user.id).first()
    image  = current_user.images.filter_by(is_active=1).first()
    if image is not None:
        print imageUploadSet.url(image.image)
        return imageUploadSet.url(image.image)
    else:
        random_img =  random.randint(1,15)
        url = url_for('static', filename='assets/images/default_profile_image/') + str(random_img) +".jpg"
        return url



# @functions - Basecamp integration methods
@login_required
def syncProjects(username):
    url='http://www.seerlabs.com:5556/api/getProject'
    user = User.query.filter_by(username=username).first()
    payload = {'email': user.email}
    response = requests.post(url, data=payload)
    responseJson = response.json()
    print(responseJson['projects'])

    for projectName in responseJson['projects']:
        print projectName
        (ret, ), = db_session.query(exists().where(Project.project_name==projectName))
        if(ret):
             project = Project.query.filter_by(project_name=projectName).first()
             user.projects.append(project)
             print "Existing"
        else:
            project = Project(projectName)
            if(add_to_db(project)):
                user.projects.append(project)
                db_session.commit()
                print "Project added"
            
def getUtilization(user):
    url='http://www.seerlabs.com:5556/api/getUtilization'
    #user = User.query.filter_by(username=user.username).first() #username is unique
    payload = {'email': user.email}
    response = requests.post(url, data=payload)
    responseJson = response.json()
    return responseJson['projects']

    #http://www.seerlabs.com:5556/api/getUtilization
    #http://www.seerlabs.com:5556/api/postNewsfeed
    #http://www.seerlabs.com:5556/api/getNewsfeed
    #http://www.seerlabs.com:5556/api/getProject

#pragma mark -Test block to install database and add a default user
def add_user(c):
    """try:"""
    db_session.add(c)
    db_session.flush()
    return True
    """except sqlalchemy.exc.IntegrityError as err:
        # @todo: handle as appropriate: return existing instance [session.query(Coupon).filter(Coupon.value==c.value).one()] or re-raise
        #logger.error("Tried to add a duplicate entry for the Coupon value [%s]. Aborting", c.value)
        print "Tried to add a duplicate entry for the Coupon value [%s]. Aborting", c.name
        return False"""
""""
init_db();
u = User('Te','re','suh', 'test@seer-technologies.com', "seer", generate_password_hash("seertech"), )
if(add_user(u)):
    db_session.commit()
else:
    print "aww"
print u.id"""

app/templates/users/change_password.html
{% from "macros.html" import render_field %}

<div class="modal fade" id="changePassword" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Change password</h4>
            </div>
            <div class="modal-body">
                <form class="form-signin" role="form" action="{{url_for('Users.change_password')}}" method="post"> 
                    <center>
                        <h2 class="form-signin-heading">Change Password</h2>
                    </center>
                    <br/>
                    {{ form.csrf_token }}
                    {{ render_field(form.old_password, placeholder="Current password", autofocus="") }}
                    <br/>
                    {{ render_field(form.new_password, placeholder="New password") }}
                    <br/>
                    {{ render_field(form.confirm_password, placeholder="Confirm password") }}
                    <br/>

                    <div class="form-group">
                        <div class="col-sm-9 col-sm-offset-3">
                            <ul id="errors">
                                {% with errors = get_flashed_messages(category_filter=["error"]) %}
                                {% if errors %}
                                <!--div-->
                                    {% for error in errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                <!--/div-->
                                {% endif %}
                                {% endwith %}
                            <ul>
                        </div>
                    </div>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Change password</button>
                </form>
            </div>
        </div>
    </div>
</div> <!-- /container -->
  

app/templates/users/login.html
{% macro render_field(field, placeholder=None) %}
{% if field.errors %}
<div>
{% elif field.flags.error %}
<div>
{% else %}
<div>
{% endif %}
    {% set css_class = 'form-control ' + kwargs.pop('class', '') %}
    {{ field(class=css_class, placeholder=placeholder, **kwargs) }}
</div>
{% endmacro %}

{% extends "layout.html" %}
{% block body %}
<div class="loginContainer">

    {% with errors = get_flashed_messages(category_filter=["error"]) %}
    {% if errors %}
    <div>
        {% for error in errors %}
            {{ error }}<br>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}

    {% if form.errors %}
    <div>
        {% for field, error in form.errors.items() %}
            {% for e in error %}
                {{ e }}<br>
            {% endfor %}
        {% endfor %}
    </div>
    {% endif %}

    <form class="form-signin" role="form" action="{{url_for('Users.login')}}" method="post">
        
        <center>
            <h2 class="form-signin-heading">Login to Iris</h2>
        </center>
        <br/><br/>
        {{ form.csrf_token }}
        {{ render_field(form.username, placeholder="Username", autofocus="") }}
        <br/>
        {{ render_field(form.password, placeholder="Password") }}
        <br/>
        <!--label class="checkbox">
            <input type="checkbox" value="remember-me"> Remember me
        </label-->
        <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
    </form>

    </div> <!-- /container -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  
</body>

{% endblock %}